### ISSUE TITLE
Consider adding some Github actions buttons

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc.github.io#88]
On the homepage, something similar to http://ghbtns.com ?
Another: http://www.buildbuttons.com/GitHub/StarButton

Something that do not track the user preferred.

**Comment by HugoGiraudel** [comment]
Why not.

**Comment by valeriangalliat** [comment]
Why not.

But if we do this, let's avoid using an external `<iframe>` (but hosting the `github-btn.html` file on sassdoc.com and using an internal `<iframe>` is okay).

And if we want to include the stars counter, I think we really don't have care about sending a JSONP request to GitHub on every page, since GitHub is already hosting sassdoc.com… it might not track much more (but otherwise I would rather not have included the counter). :cat:

**Comment by pascalduez** [comment]
It's not like it's getting us much excited. 

Wished goals:
- Straightforward (top of first page,  recognizable) and fast access to the Github repo.
- Increase stars count (supposing we give a shit about it).

As you said, Github tracking is "acceptable", but care about third parties hosting the button files.
<sup><sub>Well, we already have GA and GFonts on the page.</sup></sub>

**Comment by valeriangalliat** [comment]
Fast access to GitHub repo is nice to have, but we already have the GitHub link in the header in the new version of the site.

Stars count is not my concern. But if we find a nice place to put the button on the website, I'm not against.

**Comment by HugoGiraudel** [comment]
> Increase stars count (supposing we give a shit about it).

We do. GitHub starring helps making a project more and more popular.

**Comment by valeriangalliat** [comment]
Ok let's add a GitHub star button somewhere. You take it @HugoGiraudel?

**Comment by HugoGiraudel** [comment]
Obviously.
